name: Run Python Script Monthly

on:
  schedule:
    # Run at 10 PM CET on the 20th of each month
    - cron: '0 21 20 * *' # Adjusted for CET (-1 hour to match UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Berlin  # Set timezone to CET

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python retrieve_lta_data.py

    - name: Add and commit downloaded files
      run: |
        git config user.name "lawtseng"
        git config user.email "law050193@gmail.com"
        git add .
        git diff-index --quiet HEAD || git commit -m "Add downloaded files from script"

    - name: Push changes
      run: git push

